"""change column auteur to numero_user on table historiques

Revision ID: b75ecc1a4af8
Revises: bc2ae1883840
Create Date: 2026-08-02 17:14:19.827127

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b75ecc1a4af8'
down_revision: Union[str, Sequence[str], None] = 'bc2ae1883840'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('categories_nom_key'), 'categories', type_='unique')
    op.create_foreign_key(None, 'categories', 'categories', ['parent_id'], ['id'])
    op.create_foreign_key(None, 'statuts', 'statuts', ['parent_id'], ['id'])
    op.create_foreign_key(None, 'themes', 'themes', ['parent_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'themes', type_='foreignkey')
    op.drop_constraint(None, 'statuts', type_='foreignkey')
    op.drop_constraint(None, 'categories', type_='foreignkey')
    op.create_unique_constraint(op.f('categories_nom_key'), 'categories', ['nom'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
