"""add texte_titre, ancien/nouveau statut, numero_user to historiques

Revision ID: bc2ae1883840
Revises: 838f5deb17e8
Create Date: 2026-08-02 17:00:27.332382

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bc2ae1883840'
down_revision: Union[str, Sequence[str], None] = '838f5deb17e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('categories', 'nom',
               existing_type=sa.VARCHAR(length=150),
               nullable=True)
    op.create_index(op.f('ix_categories_couleur'), 'categories', ['couleur'], unique=False)
    op.create_index(op.f('ix_categories_description'), 'categories', ['description'], unique=False)
    op.create_index(op.f('ix_categories_id'), 'categories', ['id'], unique=False)
    op.create_index(op.f('ix_categories_nom'), 'categories', ['nom'], unique=False)
    op.create_index(op.f('ix_categories_slug'), 'categories', ['slug'], unique=False)
    op.alter_column('documents', 'nom',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('documents', 'chemin_fichier',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=True)
    op.alter_column('documents', 'nouveau_chemin',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('documents', 'date_upload',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.Date(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_constraint(op.f('documents_chemin_fichier_key'), 'documents', type_='unique')
    op.create_index(op.f('ix_documents_chemin_fichier'), 'documents', ['chemin_fichier'], unique=False)
    op.create_index(op.f('ix_documents_date_upload'), 'documents', ['date_upload'], unique=False)
    op.create_index(op.f('ix_documents_id'), 'documents', ['id'], unique=False)
    op.create_index(op.f('ix_documents_mime_type'), 'documents', ['mime_type'], unique=False)
    op.create_index(op.f('ix_documents_nom'), 'documents', ['nom'], unique=False)
    op.create_index(op.f('ix_documents_nouveau_chemin'), 'documents', ['nouveau_chemin'], unique=False)
    op.add_column('historiques', sa.Column('texte_titre', sa.String(), nullable=True))
    op.add_column('historiques', sa.Column('ancien_statut', sa.String(), nullable=True))
    op.add_column('historiques', sa.Column('nouveau_statut', sa.String(), nullable=True))
    op.add_column('historiques', sa.Column('numero_user', sa.String(), nullable=True))
    op.create_index(op.f('ix_historiques_numero_user'), 'historiques', ['numero_user'], unique=False)
    op.alter_column('historiques', 'date',
               existing_type=sa.DATE(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_DATE'))
    op.create_index(op.f('ix_historiques_date'), 'historiques', ['date'], unique=False)
    op.create_index(op.f('ix_historiques_id'), 'historiques', ['id'], unique=False)
    op.create_index(op.f('ix_historiques_nouveau_statut'), 'historiques', ['nouveau_statut'], unique=False)
    op.create_index(op.f('ix_historiques_texte_id'), 'historiques', ['texte_id'], unique=False)
    op.drop_constraint(op.f('historiques_texte_id_fkey'), 'historiques', type_='foreignkey')
    op.create_foreign_key(None, 'historiques', 'textes', ['texte_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(
        op.f('historiques_numero_user_fkey'), 'historiques', 'users',
        ['numero_user'], ['numero'], ondelete='SET NULL'
    )
    op.drop_column('historiques', 'statut')
    op.alter_column('liens_utiles', 'titre',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True,
               existing_server_default=sa.text("''::text"))
    op.alter_column('liens_utiles', 'url',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=True)
    op.alter_column('liens_utiles', 'entite',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.create_index(op.f('ix_liens_utiles_entite'), 'liens_utiles', ['entite'], unique=False)
    op.create_index(op.f('ix_liens_utiles_id'), 'liens_utiles', ['id'], unique=False)
    op.create_index(op.f('ix_liens_utiles_titre'), 'liens_utiles', ['titre'], unique=False)
    op.create_index(op.f('ix_liens_utiles_url'), 'liens_utiles', ['url'], unique=False)
    op.drop_constraint(op.f('liens_utiles_texte_id_fkey'), 'liens_utiles', type_='foreignkey')
    op.create_foreign_key(None, 'liens_utiles', 'textes', ['texte_id'], ['id'])
    op.alter_column('statuts', 'nom',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.drop_constraint(op.f('statuts_nom_key'), 'statuts', type_='unique')
    op.create_index(op.f('ix_statuts_couleur'), 'statuts', ['couleur'], unique=False)
    op.create_index(op.f('ix_statuts_description'), 'statuts', ['description'], unique=False)
    op.create_index(op.f('ix_statuts_id'), 'statuts', ['id'], unique=False)
    op.create_index(op.f('ix_statuts_nom'), 'statuts', ['nom'], unique=False)
    op.create_index(op.f('ix_statuts_slug'), 'statuts', ['slug'], unique=False)
    op.alter_column('textes', 'titre',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=True)
    op.alter_column('textes', 'resume',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('textes', 'mots_cles',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('textes', 'contenu_html',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.create_index(op.f('ix_textes_date_mise_en_vigueur'), 'textes', ['date_mise_en_vigueur'], unique=False)
    op.create_index(op.f('ix_textes_id'), 'textes', ['id'], unique=False)
    op.create_index(op.f('ix_textes_mots_cles'), 'textes', ['mots_cles'], unique=False)
    op.create_index(op.f('ix_textes_numero'), 'textes', ['numero'], unique=False)
    op.create_index(op.f('ix_textes_signataire_nom'), 'textes', ['signataire_nom'], unique=False)
    op.create_index(op.f('ix_textes_signataire_titre'), 'textes', ['signataire_titre'], unique=False)
    op.create_index(op.f('ix_textes_titre'), 'textes', ['titre'], unique=False)
    op.drop_constraint(op.f('textes_statut_id_fkey'), 'textes', type_='foreignkey')
    op.drop_constraint(op.f('textes_categorie_id_fkey'), 'textes', type_='foreignkey')
    op.create_foreign_key(None, 'textes', 'statuts', ['statut_id'], ['id'])
    op.create_foreign_key(None, 'textes', 'categories', ['categorie_id'], ['id'])
    op.drop_constraint(op.f('textes_documents_texte_id_fkey'), 'textes_documents', type_='foreignkey')
    op.drop_constraint(op.f('textes_documents_document_id_fkey'), 'textes_documents', type_='foreignkey')
    op.create_foreign_key(None, 'textes_documents', 'documents', ['document_id'], ['id'])
    op.create_foreign_key(None, 'textes_documents', 'textes', ['texte_id'], ['id'])
    op.alter_column('textes_reference', 'titre',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('textes_reference', 'lien_url',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.create_index(op.f('ix_textes_reference_categorie'), 'textes_reference', ['categorie'], unique=False)
    op.create_index(op.f('ix_textes_reference_date_mise_en_vigueur'), 'textes_reference', ['date_mise_en_vigueur'], unique=False)
    op.create_index(op.f('ix_textes_reference_id'), 'textes_reference', ['id'], unique=False)
    op.create_index(op.f('ix_textes_reference_lien_url'), 'textes_reference', ['lien_url'], unique=False)
    op.create_index(op.f('ix_textes_reference_numero'), 'textes_reference', ['numero'], unique=False)
    op.create_index(op.f('ix_textes_reference_statut'), 'textes_reference', ['statut'], unique=False)
    op.create_index(op.f('ix_textes_reference_titre'), 'textes_reference', ['titre'], unique=False)
    op.drop_constraint(op.f('textes_reference_texte_lie_id_fkey'), 'textes_reference', type_='foreignkey')
    op.drop_constraint(op.f('textes_reference_texte_id_fkey'), 'textes_reference', type_='foreignkey')
    op.create_foreign_key(None, 'textes_reference', 'textes', ['texte_id'], ['id'])
    op.drop_constraint(op.f('textes_themes_texte_id_fkey'), 'textes_themes', type_='foreignkey')
    op.drop_constraint(op.f('textes_themes_theme_id_fkey'), 'textes_themes', type_='foreignkey')
    op.create_foreign_key(None, 'textes_themes', 'textes', ['texte_id'], ['id'])
    op.create_foreign_key(None, 'textes_themes', 'themes', ['theme_id'], ['id'])
    op.alter_column('themes', 'nom',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
    op.create_index(op.f('ix_themes_couleur'), 'themes', ['couleur'], unique=False)
    op.create_index(op.f('ix_themes_description'), 'themes', ['description'], unique=False)
    op.create_index(op.f('ix_themes_id'), 'themes', ['id'], unique=False)
    op.create_index(op.f('ix_themes_nom'), 'themes', ['nom'], unique=False)
    op.create_index(op.f('ix_themes_slug'), 'themes', ['slug'], unique=False)
    op.drop_constraint(op.f('themes_parent_id_fkey'), 'themes', type_='foreignkey')
    op.alter_column('users', 'numero',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'numero',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint(None, 'themes', type_='foreignkey')
    op.create_foreign_key(op.f('themes_parent_id_fkey'), 'themes', 'themes', ['parent_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_themes_slug'), table_name='themes')
    op.drop_index(op.f('ix_themes_nom'), table_name='themes')
    op.drop_index(op.f('ix_themes_id'), table_name='themes')
    op.drop_index(op.f('ix_themes_description'), table_name='themes')
    op.drop_index(op.f('ix_themes_couleur'), table_name='themes')
    op.alter_column('themes', 'nom',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
    op.drop_constraint(None, 'textes_themes', type_='foreignkey')
    op.drop_constraint(None, 'textes_themes', type_='foreignkey')
    op.create_foreign_key(op.f('textes_themes_theme_id_fkey'), 'textes_themes', 'themes', ['theme_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('textes_themes_texte_id_fkey'), 'textes_themes', 'textes', ['texte_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'textes_reference', type_='foreignkey')
    op.create_foreign_key(op.f('textes_reference_texte_id_fkey'), 'textes_reference', 'textes', ['texte_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('textes_reference_texte_lie_id_fkey'), 'textes_reference', 'textes', ['texte_lie_id'], ['id'])
    op.drop_index(op.f('ix_textes_reference_titre'), table_name='textes_reference')
    op.drop_index(op.f('ix_textes_reference_statut'), table_name='textes_reference')
    op.drop_index(op.f('ix_textes_reference_numero'), table_name='textes_reference')
    op.drop_index(op.f('ix_textes_reference_lien_url'), table_name='textes_reference')
    op.drop_index(op.f('ix_textes_reference_id'), table_name='textes_reference')
    op.drop_index(op.f('ix_textes_reference_date_mise_en_vigueur'), table_name='textes_reference')
    op.drop_index(op.f('ix_textes_reference_categorie'), table_name='textes_reference')
    op.alter_column('textes_reference', 'lien_url',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('textes_reference', 'titre',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_constraint(None, 'textes_documents', type_='foreignkey')
    op.drop_constraint(None, 'textes_documents', type_='foreignkey')
    op.create_foreign_key(op.f('textes_documents_document_id_fkey'), 'textes_documents', 'documents', ['document_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('textes_documents_texte_id_fkey'), 'textes_documents', 'textes', ['texte_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'textes', type_='foreignkey')
    op.drop_constraint(None, 'textes', type_='foreignkey')
    op.create_foreign_key(op.f('textes_categorie_id_fkey'), 'textes', 'categories', ['categorie_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('textes_statut_id_fkey'), 'textes', 'statuts', ['statut_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_textes_titre'), table_name='textes')
    op.drop_index(op.f('ix_textes_signataire_titre'), table_name='textes')
    op.drop_index(op.f('ix_textes_signataire_nom'), table_name='textes')
    op.drop_index(op.f('ix_textes_numero'), table_name='textes')
    op.drop_index(op.f('ix_textes_mots_cles'), table_name='textes')
    op.drop_index(op.f('ix_textes_id'), table_name='textes')
    op.drop_index(op.f('ix_textes_date_mise_en_vigueur'), table_name='textes')
    op.alter_column('textes', 'contenu_html',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('textes', 'mots_cles',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('textes', 'resume',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('textes', 'titre',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=False)
    op.drop_constraint(None, 'statuts', type_='foreignkey')
    op.drop_index(op.f('ix_statuts_slug'), table_name='statuts')
    op.drop_index(op.f('ix_statuts_nom'), table_name='statuts')
    op.drop_index(op.f('ix_statuts_id'), table_name='statuts')
    op.drop_index(op.f('ix_statuts_description'), table_name='statuts')
    op.drop_index(op.f('ix_statuts_couleur'), table_name='statuts')
    op.create_unique_constraint(op.f('statuts_nom_key'), 'statuts', ['nom'], postgresql_nulls_not_distinct=False)
    op.alter_column('statuts', 'nom',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.drop_constraint(None, 'liens_utiles', type_='foreignkey')
    op.create_foreign_key(op.f('liens_utiles_texte_id_fkey'), 'liens_utiles', 'textes', ['texte_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_liens_utiles_url'), table_name='liens_utiles')
    op.drop_index(op.f('ix_liens_utiles_titre'), table_name='liens_utiles')
    op.drop_index(op.f('ix_liens_utiles_id'), table_name='liens_utiles')
    op.drop_index(op.f('ix_liens_utiles_entite'), table_name='liens_utiles')
    op.alter_column('liens_utiles', 'entite',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('liens_utiles', 'url',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=False)
    op.alter_column('liens_utiles', 'titre',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("''::text"))
    op.drop_constraint(op.f('historiques_numero_user_fkey'), 'historiques', type_='foreignkey')
    op.add_column('historiques', sa.Column('statut', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'historiques', type_='foreignkey')
    op.create_foreign_key(op.f('historiques_texte_id_fkey'), 'historiques', 'textes', ['texte_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_historiques_texte_id'), table_name='historiques')
    op.drop_index(op.f('ix_historiques_nouveau_statut'), table_name='historiques')
    op.drop_index(op.f('ix_historiques_numero_user'), table_name='historiques')
    op.drop_index(op.f('ix_historiques_id'), table_name='historiques')
    op.drop_index(op.f('ix_historiques_date'), table_name='historiques')
    op.alter_column('historiques', 'date',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.DATE(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_DATE'))
    op.drop_column('historiques', 'numero_user')
    op.drop_column('historiques', 'nouveau_statut')
    op.drop_column('historiques', 'ancien_statut')
    op.drop_column('historiques', 'texte_titre')
    op.drop_index(op.f('ix_documents_nouveau_chemin'), table_name='documents')
    op.drop_index(op.f('ix_documents_nom'), table_name='documents')
    op.drop_index(op.f('ix_documents_mime_type'), table_name='documents')
    op.drop_index(op.f('ix_documents_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_date_upload'), table_name='documents')
    op.drop_index(op.f('ix_documents_chemin_fichier'), table_name='documents')
    op.create_unique_constraint(op.f('documents_chemin_fichier_key'), 'documents', ['chemin_fichier'], postgresql_nulls_not_distinct=False)
    op.alter_column('documents', 'date_upload',
               existing_type=sa.Date(),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('documents', 'nouveau_chemin',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('documents', 'chemin_fichier',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=False)
    op.alter_column('documents', 'nom',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_constraint(None, 'categories', type_='foreignkey')
    op.drop_index(op.f('ix_categories_slug'), table_name='categories')
    op.drop_index(op.f('ix_categories_nom'), table_name='categories')
    op.drop_index(op.f('ix_categories_id'), table_name='categories')
    op.drop_index(op.f('ix_categories_description'), table_name='categories')
    op.drop_index(op.f('ix_categories_couleur'), table_name='categories')
    op.create_unique_constraint(op.f('categories_nom_key'), 'categories', ['nom'], postgresql_nulls_not_distinct=False)
    op.alter_column('categories', 'nom',
               existing_type=sa.VARCHAR(length=150),
               nullable=False)
    # ### end Alembic commands ###