from src.backend.models.categorie import Categorie
from src.backend.models.document import Document
from src.backend.models.historique import Historique
from src.backend.models.lien_utile import Liens_Utile
from src.backend.models.statut import Statut
from src.backend.models.texte_document import Texte_Document
from src.backend.models.texte_reference import Texte_Reference
from src.backend.models.texte_theme import Texte_Theme
from src.backend.models.texte import Texte
from src.backend.models.theme import Theme